apiVersion: 1
datasources:
  - name: InfluxDB
    type: influxdb
    uid: influxdb-jmx-metrics
    access: proxy
    url: http://influxdb:8086
    editable: true
    database: db0
    jsonData:
      version: Flux
      organization: Nutanix
      defaultBucket: tomcat_metrics
      tlsSkipVerify: true
    secureJsonData:
      token: ${INFLUXDB_API_TOKEN}

  - name: Prometheus
    type: prometheus
    uid: prometheus-ds1
    url: http://prometheus:9090
    editable: true
    jsonData:
      timeInterval: 15s

  - name: JSON API for Apache Drill
    uid: json-api-drill
    type: marcusolsson-json-datasource
    url: http://drill:8047
    editable: true
    jsonData:
      timeout: 120